name: CI  Prettier 格式化

on:
  push:
    branches:
      - development

env:
  NODE_VERSION: 20.11.1

jobs:
  lint:
    name: 代码检查
    runs-on: ubuntu-latest
    env:
      RELEASE_CHANNEL: ${{ inputs.environment }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref }}
          submodules: recursive
      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: 推送元数据更改
        run: |
          yarn prettier --write "./**/*.{ts,tsx,js,json,jsx,scss,html,yaml,yml}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./**/*.{ts,tsx,js,json,jsx,scss,html,yaml,yml}
          git commit -m "Update CI"
          git push
