name: Auto Delete Tags

on:
  push:

jobs:
  delete-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Tags
        run: |
          git fetch --prune --tags
          git tag -l | xargs -n 1 git push --delete origin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
