name: tags

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.3
      
    - name: Set up JDK 16
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 16
        
    - name: Delete untagged ghcr
      uses: Chizkiyahu/delete-untagged-ghcr-action@v3
      with:
          # Personal access token (PAT) used to fetch the repository. The PAT is configured
          # with the local git config, which enables your scripts to run authenticated git
          # commands. The post-job step removes the PAT.
          # needs delete:packages permissions
          # required: true
          # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
          token: ${{ secrets.PAT_TOKEN }}
          # Repository name or  name with owner
          # Delete only from repository name
          # Default: ${{ github.repository }}
          repository: ''
          # 'The repository owner name'
          # Default: ${{ github.repository_owner }}
          repository_owner: ''
          # 'The package name'
          # Delete only from package name
          # required: false
          package_name: ''
          # Delete only package versions without tag
          # required: false
          # Default: true
          # choices: true, false
          untagged_only: true
          # Except untagged multiplatform packages from deletion 
          # only for untagged_only=true
          # needs docker installed
          except_untagged_multiplatform: false
          # the owner type
          # required: true
          # choices: org, user
          owner_type: ''
      